### ISSUE TITLE
History of data in Eve.app

### ISSUE THREAD

**Issue by straubus** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#1]
Hi! 👋 I cannot see history of measurements in eve.app, could You add this functionality?

**Comment by HomeKidd** [comment]
Hi! History is a very complex thing and at the moment its not supported! I’m working on that feature nearly more than one year now but still cant get working properly! 😩 until i cant make it reliable it will be on my ToDo list!🙃
