### ISSUE TITLE
[Client 3] Failed to compute SRP shared secret (code -2)

### ISSUE THREAD

**Issue by vvlang** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#10]
![1581851559395](https://user-images.githubusercontent.com/45045804/74603607-5106e180-50f0-11ea-8358-bdc2327dee38.jpg)

**Comment by HomeKidd** [comment]
Hi! Thats a common issue due to high memory usage in esp-homekit, simply just restart the esp and try again as i’ve mentioned in the [Setup Wiki page](https://github.com/HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve/wiki/Setup#homekit-setup)! ✌️

**Comment by vvlang** [comment]
Resetting device to factory defaults not solved，Version 1.0.4 is normal！

**Comment by HomeKidd** [comment]
Not resetting, simply just restarting aka unplug the power and repower it✌️

**Comment by vvlang** [comment]
You are really a talented！！！

**Comment by HomeKidd** [comment]
Is it working now?

**Comment by vvlang** [comment]
Yes！！
![WechatIMG80](https://user-images.githubusercontent.com/45045804/74605382-a0eea400-5102-11ea-8b3c-1c07c8d445c5.jpeg)
