### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by MarijnDoeve** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#21]
Hi!

It is possible to compile this for the ESP32? I noticed there is no source code in this repo.

I'm especially interested in the 1.x version (so without an OLED).

**Comment by HomeKidd** [comment]
Hi!

This firmware is only available for ESP8266 because of costs and easier implementation of HomeKit. 
Since it has a custom PCB, ESP8266 needs only 3 components and the price is 1/3 of an ESP32.
