### ISSUE TITLE
Question: Bluetooth active or not?

### ISSUE THREAD

**Issue by Caleb79** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#23]
Hi, as the headline already says, my question is if BT is activated or not?
The reason why I'm asking is, I have a BT device which I neither cannot identify nor that I'm aware of one.
Thanks.

**Comment by HomeKidd** [comment]
Hi!

Read issue #3 

> This project uses the Apple HomeKit accessory server library [ESP-HomeKit](https://github.com/maximkulkin/esp-homekit) from [@MaximKulkin](https://github.com/maximkulkin) for [ESP-OPEN-RTOS](https://github.com/SuperHouse/esp-open-rtos)

ESP-HomeKit uses HomeKit over IP protocol, so theres no support for bluetooth.
Also the ESP8266 _- which all my projects are using -_  doesn't have bluetooth capabilities
