### ISSUE TITLE
How to turn the display off?

### ISSUE THREAD

**Issue by pawelosin** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#4]
The display works all the time.  How to turn it off?  The switch connected to gpio0 and gnd does not work.

**Comment by HomeKidd** [comment]
First things first which version do you running? The latest 2.0.4? You’ve connected a button or a switch to GPIO0? 3 of my Wemoses are working properly with 2.0.4 and always turn off the display after 5 minutes 😅

**Comment by HomeKidd** [comment]
Also please post an image of the setup, GPIO connections🤓

**Comment by pawelosin** [comment]
I installed the latest version 2.0.4 and now it's ok. Thanks a lot.
