### ISSUE TITLE
No visible access point

### ISSUE THREAD

**Issue by straubus** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#5]
Hi i have flashed Wemos with >v2.0 soft and on any of them Wemos can't broadcast wifi signal. On v1.0.4 everything is ok. What is the problem?

**Comment by HomeKidd** [comment]
Did you ereased the flash before you updating to 2.0.x? It sounds like the Wi-fi settings kept due to skipping ereasing flash🤓

**Comment by straubus** [comment]
yes, erased It every time. I am using even a brand new Wemos. Stil the same result, v1.04 works properly, v2xx does not.

**Comment by straubus** [comment]
I think I have found a reason of this issue. I have tried to add it to HomeKit before connecting bme and oled to Wemos. it seems to work after proper connection
