### ISSUE TITLE
didn't work for me

### ISSUE THREAD

**Issue by ta4ukoma** [HomeKidd/ESP8266-HomeKit-Weather-Station-BME280-Elgato-Eve#8]
Hi! I'm trying to copy you project with esp8266 NodeMCU. Did all as you wrot in wiki, but ...
![meteoespHomekid](https://user-images.githubusercontent.com/29577500/70044691-e4da0e80-15d3-11ea-92d3-df8f7a57a7ab.png)
Flash is allright, but ssid did't see.
Can you help me ?
Sorry for my English, just yet study.

**Comment by HomeKidd** [comment]
Hi!

Actually error message shows that **"Please use the equivalent size '4MB'**.
So your correct flash parameters:

```
esptool.py -p /dev/<your_ESPPort> --baud 115200 write_flash -fs 4MB-fm dout -ff 40m \
0x0 rboot.bin 0x1000 blank_config.bin 0x2000 otaboot.bin
```

Also read #5 Issue, this maybe help!

**Comment by ta4ukoma** [comment]
Thx a lot for helping =) your advice helped.
But I has a new problem. Wifi ssid again didn't visible and I connected to console esp on baudrate 115200 and saw this:
![meteoespHomekid1](https://user-images.githubusercontent.com/29577500/70048102-9b40f200-15da-11ea-8308-40f7a1d5cb6a.png)
Without bme280 and lcd will not work ? I'm connected lcd and bme280 at the same pin like on you pics, but I have nodemcu against you wemos.

**Comment by HomeKidd** [comment]
Yes without the BME280 and OLED the Wifi settings won't come up.

Make sure you have the right connections:

**BME 280 pins:**
`SCL =  GPIO5  - D1 on NodeMCU`
`SDA =  GPIO4 - D2 on NodeMCU`

**OLED Screen pins:**

`SCL =  GPIO14  - D5 on NodeMCU`
`SDA =  GPIO13 - D7 on NodeMCU`

Also make sure to have both the sensor and screen connected to 3.3V! Read Issue #6 why!

**Comment by ta4ukoma** [comment]
again, thx a lot! It turns out I do not have such a sensor and screen that are required ) buy them the other day and get back to you

**Comment by ta4ukoma** [comment]
WoW! It's working amazing! 
But can I take pressure in mm against hPa ?

**Comment by HomeKidd** [comment]
@ta4ukoma Great!

Sorry but only hPa and inHg are available (HomeKit only can switch between these two)!
